export const ADD_ACTIVITIES = 'ADD_ACTIVITIES';
export const ACTIVITIES_LOADING = 'ACTIVITIES_LOADING';
export const ACTIVITIES_FAILED = 'ACTIVITIES_FAILED';

export const ADD_HIKING = 'ADD_HIKING';
export const HIKING_LOADING = 'HIKING_LOADING';
export const HIKING_FAILED = 'HIKING_FAILED';

export const ADD_BIKING = 'ADD_BIKING';
export const BIKING_LOADING = 'BIKING_LOADING';
export const BIKING_FAILED = 'BIKING_FAILED';

export const ADD_KAYAKING = 'ADD_KAYAKING';
export const KAYAKING_LOADING = 'KAYAKING_LOADING';
export const KAYAKING_FAILED = 'KAYAKING_FAILED';

export const ADD_FISHING = 'ADD_FISHING';
export const FISHING_LOADING = 'FISHING_LOADING';
export const FISHING_FAILED = 'FISHING_FAILED';

export const ADD_CAMPING = 'ADD_CAMPING';
export const CAMPING_LOADING = 'CAMPING_LOADING';
export const CAMPING_FAILED = 'CAMPING_FAILED';

export const ADD_CLIMBING = 'ADD_CLIMBING';
export const CLIMBING_LOADING = 'CLIMBING_LOADING';
export const CLIMBING_FAILED = 'CLIMBING_FAILED';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const ADD_COMMENT = 'ADD_COMMENT';

export const ADD_FAVORITES = 'ADD_FAVORITES';
export const FAVORITES_LOADING = 'FAVORITES_LOADING';
export const FAVORITES_FAILED = 'FAVORITES_FAILED';